import{a as f,S as m,N as w,K as y,P as v,i as g,A as h,e as u,h as b,p as L}from"./assets/vendor-fb7620e2.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))o(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function i(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(s){if(s.ep)return;s.ep=!0;const r=i(s);fetch(s.href,r)}})();document.getElementById("profile-link").addEventListener("click",function(t){t.preventDefault(),document.getElementById("profile").classList.toggle("active");const e=document.getElementById("dropdown");e.classList.contains("active")?(e.classList.remove("active"),e.style.opacity=0):(e.classList.add("active"),setTimeout(()=>{e.style.opacity=1},10))});const N="https://portfolio-js.b.goit.study/api";async function O(t){const i=`${N}/reviews`;try{return(await f.get(i)).data}catch(o){throw console.error("Error fetching images:",o),o}}const p=document.querySelector(".reviews-list");function P(t,e,i,o){return`
     <li class="reviews-list-items swiper-slide" data-id="${t}">
     <img class="reviews-image" src="${i}" alt="Photo" 
            width="48"
            height="48"
            loading="lazy" />
          <div class="reviews-text-content">
            <h3 class="reviews-name-header">${e}</h3>
            <p class="reviews-main-text">${o}</p>
          </div>
        </li>
  `}function d(){const t='<p class="end-message">Not found</p>';p.insertAdjacentHTML("afterend",t)}function E(t){return t.map(({_id:e,author:i,avatar_url:o,review:s})=>P(e,i,o,s)).join("")}function T(t){const e=E(t);p.insertAdjacentHTML("beforeend",e)}const B=document.querySelector(".swiper"),n=document.querySelector(".button-next-svg"),a=document.querySelector(".button-prev"),I=new m(B,{modules:[w,y,v],navigation:{nextEl:n,prevEl:a},direction:"horizontal",autoHeight:!1,autoWidth:!1,watchOverflow:!0,keyboard:{enabled:!0,onlyInViewport:!0,pageUpDown:!0},breakpoints:{320:{slidesPerView:"auto",spaceBetween:18},767:{slidesPerView:2,spaceBetween:16},1280:{slidesPerView:3,spaceBetween:16},1440:{slidesPerView:4,spaceBetween:16}}});I.update();async function x(){try{const t=await O();t.length===0?d():T(t)}catch{g.error({color:"red",message:"❌ Sorry, there is an error. Please try again later!",position:"topRight"}),d()}}const R=new MutationObserver(t=>{t.forEach(e=>{e.attributeName==="class"&&(n.classList.contains("swiper-button-disabled")?(n.style.opacity="0.5",n.style.cursor="not-allowed"):(n.style.opacity="1",n.style.cursor="pointer"))})});R.observe(n,{attributes:!0});const S=new MutationObserver(t=>{t.forEach(e=>{e.attributeName==="class"&&(a.classList.contains("swiper-button-disabled")?(a.style.opacity="0.5",a.style.cursor="not-allowed"):(a.style.opacity="1",a.style.cursor="pointer"))})});S.observe(a,{attributes:!0});x();new h(".faq-list",{duration:400,showMultiple:!0});const l=u();l.use(b());l.use(u.static(L.join(__dirname,"src"),{maxAge:"30d"}));l.listen();
//# sourceMappingURL=commonHelpers.js.map
